CREATE TABLE VEM_SER.ESTUDANTE(
id_estudante NUMBER PRIMARY KEY,
nome VARCHAR(200) NOT NULL,
data_nascimento DATE NOT NULL,
nr_matricula NUMBER(10) UNIQUE NOT NULL,
ativo CHAR(1) 
);

CREATE SEQUENCE VEM_SER.SEQ_ESTUDANTE
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

INSERT INTO VEM_SER.ESTUDANTE(ID_ESTUDANTE,NOME,DATA_NASCIMENTO,NR_MATRICULA,ATIVO)
VALUES(VEM_SER.SEQ_ESTUDANTE.NEXTVAL,'JHENNYFER SOBRINHO',TO_DATE('06-12-1995','dd-mm-yyyy'),1234598765,'S');

INSERT INTO VEM_SER.ESTUDANTE(ID_ESTUDANTE,NOME,DATA_NASCIMENTO,NR_MATRICULA,ATIVO)
VALUES(VEM_SER.SEQ_ESTUDANTE.NEXTVAL,'MARIA FERNANDES',TO_DATE('07-10-1997','dd-mm-yyyy'),1234598766,'S');

INSERT INTO VEM_SER.ESTUDANTE(ID_ESTUDANTE,NOME,DATA_NASCIMENTO,NR_MATRICULA,ATIVO)
VALUES(VEM_SER.SEQ_ESTUDANTE.NEXTVAL,'CASSIA FERNANDES',TO_DATE('07-02-1998','dd-mm-yyyy'),1234598767,'S');

INSERT INTO VEM_SER.ESTUDANTE(ID_ESTUDANTE,NOME,DATA_NASCIMENTO,NR_MATRICULA,ATIVO)
VALUES(VEM_SER.SEQ_ESTUDANTE.NEXTVAL,'MARCUS ANTUNIUS',TO_DATE('22-11-1999','dd-mm-yyyy'),1234598768,'S');

INSERT INTO VEM_SER.ESTUDANTE(ID_ESTUDANTE,NOME,DATA_NASCIMENTO,NR_MATRICULA,ATIVO)
VALUES(VEM_SER.SEQ_ESTUDANTE.NEXTVAL,'ROBERTO SANTOS',TO_DATE('09-05-1992','dd-mm-yyyy'),1234598769,'S');

INSERT INTO VEM_SER.ESTUDANTE(ID_ESTUDANTE,NOME,DATA_NASCIMENTO,NR_MATRICULA,ATIVO)
VALUES(VEM_SER.SEQ_ESTUDANTE.NEXTVAL,'MIRIAN MENDES',TO_DATE('16-02-1994','dd-mm-yyyy'),1234598770,'N');

INSERT INTO VEM_SER.ESTUDANTE(ID_ESTUDANTE,NOME,DATA_NASCIMENTO,NR_MATRICULA,ATIVO)
VALUES(VEM_SER.SEQ_ESTUDANTE.NEXTVAL,'JULIA NASCIMENTO',TO_DATE('09-12-1993','dd-mm-yyyy'),1234598771,'S');

INSERT INTO VEM_SER.ESTUDANTE(ID_ESTUDANTE,NOME,DATA_NASCIMENTO,NR_MATRICULA,ATIVO)
VALUES(VEM_SER.SEQ_ESTUDANTE.NEXTVAL,'JOAO SANTOS',TO_DATE('06-11-1996','dd-mm-yyyy'),1234598772,'S');

INSERT INTO VEM_SER.ESTUDANTE(ID_ESTUDANTE,NOME,DATA_NASCIMENTO,NR_MATRICULA,ATIVO)
VALUES(VEM_SER.SEQ_ESTUDANTE.NEXTVAL,'ANA REITZ',TO_DATE('08-12-1994','dd-mm-yyyy'),1234598773,'S');

INSERT INTO VEM_SER.ESTUDANTE(ID_ESTUDANTE,NOME,DATA_NASCIMENTO,NR_MATRICULA,ATIVO)
VALUES(VEM_SER.SEQ_ESTUDANTE.NEXTVAL,'FERNANDO SILVA',TO_DATE('06-06-1999','dd-mm-yyyy'),1234598774,'S');

SELECT *FROM VEM_SER.ESTUDANTE;